package com.shashank.splitterexpensemanager.core

const val ROOM_DB: String = "RoomDb"
const val GROUP_ID: String = "GroupId"
const val PAYER_ID: String = "PayerId"
const val RECEIVER_ID: String = "ReceiverId"
const val AMOUNT: String = "Amount"
const val EXPENSES_ID: String = "ExpensesId"
const val PERSON_ID: String = "PersonId"
const val FRIEND_ID: String = "FriendId"
const val IS_PERSON_IN_GROUP: String = "is person in group"
const val PERSON: String = "Person"
const val CATEGORY: String = "Category"
const val GROUP_MEMBER: String = "GroupMember"
const val SHARED_PREFERENCES: String = "mySharedPreferences"
const val UPDATE_EXPENSES: String = "UpdateExpense"
const val UPDATE_GROUP: String = "UpdateGroup"